name: flutter_keuanganku
description: "Keuanganku — Neobrutalist High-Contrast Budget Tracker in Flutter & Dart"
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  lucide_flutter: ^1.0.0
  fl_chart: ^0.66.0
  shared_preferences: ^2.2.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
